In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
m1 = a.reshape(2,3,2)
m2 = np.transpose(a.reshape(2,3,2),(1,2,0))

print(m1.shape)
print(m2.shape)
print('')
print(m1)
print('')
print(m2)

(2, 3, 2)
(3, 2, 2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

[[[ 1  7]
  [ 2  8]]

 [[ 3  9]
  [ 4 10]]

 [[ 5 11]
  [ 6 12]]]


In [ ]:
a = np.array([1, 2, 3, 4])
m1 = a.reshape(2,2)
m2 = np.transpose(a.reshape(2,2))

print(m1.shape)
print(m2.shape)
print('')
print(m1)
print('')
print(m2)

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
m1 = a.reshape(3,2,2)
print(m1.shape)
print('')
print(m1)

In [2]:
import util

#print(util.translateDicc()[0])



In [3]:
print(m1)
print(util.customNormalize(m1))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[0.         0.09090909]
  [0.18181818 0.27272727]
  [0.36363636 0.45454545]]

 [[0.54545455 0.63636364]
  [0.72727273 0.81818182]
  [0.90909091 1.        ]]]


In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])