In [11]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
m1 = a.reshape(2,3,2)
m2 = np.transpose(a.reshape(2,3,2),(1,2,0))

print(m1.shape)
print(m2.shape)
print('')
print(m1)
print('')
print(m2)

(2, 3, 2)
(3, 2, 2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

[[[ 1  7]
  [ 2  8]]

 [[ 3  9]
  [ 4 10]]

 [[ 5 11]
  [ 6 12]]]


In [13]:
a = np.array([1, 2, 3, 4])
m1 = a.reshape(2,2)
m2 = np.transpose(a.reshape(2,2))

print(m1.shape)
print(m2.shape)
print('')
print(m1)
print('')
print(m2)

(2, 2)
(2, 2)

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [14]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
m1 = a.reshape(3,2,2)
print(m1.shape)
print('')
print(m1)

(3, 2, 2)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
